### ISSUE TITLE
Step 3 libraries not importing

### ISSUE THREAD

**Issue by mhuzaif2** [ihmcrobotics/dynamic-walking-2018#1]
I have successfully finished Steps 1 and 2 given on the tutorial page. However, on the third one, I am facing issues with the import commands. Following is the error I receive:

'The import us.ihmc.euclid.Axis' could not be resolved.'

**Comment by dljsjr** [comment]
@mhuzaif2 If you're still having this issue, come find me during a break. I'm sitting in the very back on the couch.

Note that you need to be connected to the Internet while importing projects.
